# Generated by Django 5.2 on 2025-04-16 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeling', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('colors_type', models.CharField(choices=[('Oil', 'Oil'), ('Acrylics', 'Acrylics'), ('Watercolor', 'Watercolor'), ('Pencil', 'Pencil')], default='Oil', max_length=20)),
                ('year_created', models.PositiveIntegerField()),
                ('style', models.CharField(max_length=100)),
                ('mood', models.ManyToManyField(to='main_app.mood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('colors', models.TextField()),
                ('note', models.TextField(max_length=50)),
                ('painting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.painting')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
